//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "WebService1Soap", Namespace = "http://tempuri.org/")]
public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback ShowBuildingsOperationCompleted;

    private System.Threading.SendOrPostCallback ShowOfficesOperationCompleted;

    /// <remarks/>
    public WebService1()
    {
        this.Url = "http://localhost/TechnologicalUnemployment4/WebService1.asmx";
    }

    /// <remarks/>
    public event ShowBuildingsCompletedEventHandler ShowBuildingsCompleted;

    /// <remarks/>
    public event ShowOfficesCompletedEventHandler ShowOfficesCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowBuildings", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Building[] ShowBuildings()
    {
        object[] results = this.Invoke("ShowBuildings", new object[0]);
        return ((Building[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginShowBuildings(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ShowBuildings", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public Building[] EndShowBuildings(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Building[])(results[0]));
    }

    /// <remarks/>
    public void ShowBuildingsAsync()
    {
        this.ShowBuildingsAsync(null);
    }

    /// <remarks/>
    public void ShowBuildingsAsync(object userState)
    {
        if ((this.ShowBuildingsOperationCompleted == null))
        {
            this.ShowBuildingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowBuildingsOperationCompleted);
        }
        this.InvokeAsync("ShowBuildings", new object[0], this.ShowBuildingsOperationCompleted, userState);
    }

    private void OnShowBuildingsOperationCompleted(object arg)
    {
        if ((this.ShowBuildingsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ShowBuildingsCompleted(this, new ShowBuildingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowOffices", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Office[] ShowOffices()
    {
        object[] results = this.Invoke("ShowOffices", new object[0]);
        return ((Office[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginShowOffices(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ShowOffices", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public Office[] EndShowOffices(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Office[])(results[0]));
    }

    /// <remarks/>
    public void ShowOfficesAsync()
    {
        this.ShowOfficesAsync(null);
    }

    /// <remarks/>
    public void ShowOfficesAsync(object userState)
    {
        if ((this.ShowOfficesOperationCompleted == null))
        {
            this.ShowOfficesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowOfficesOperationCompleted);
        }
        this.InvokeAsync("ShowOffices", new object[0], this.ShowOfficesOperationCompleted, userState);
    }

    private void OnShowOfficesOperationCompleted(object arg)
    {
        if ((this.ShowOfficesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ShowOfficesCompleted(this, new ShowOfficesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class Building
{

    private string addressField;

    /// <remarks/>
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class Office
{

    private string officeNumberField;

    private string buildingAddressField;

    private string ventilationSettingField;

    private int temperatureSettingField;

    /// <remarks/>
    public string OfficeNumber
    {
        get
        {
            return this.officeNumberField;
        }
        set
        {
            this.officeNumberField = value;
        }
    }

    /// <remarks/>
    public string BuildingAddress
    {
        get
        {
            return this.buildingAddressField;
        }
        set
        {
            this.buildingAddressField = value;
        }
    }

    /// <remarks/>
    public string VentilationSetting
    {
        get
        {
            return this.ventilationSettingField;
        }
        set
        {
            this.ventilationSettingField = value;
        }
    }

    /// <remarks/>
    public int TemperatureSetting
    {
        get
        {
            return this.temperatureSettingField;
        }
        set
        {
            this.temperatureSettingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void ShowBuildingsCompletedEventHandler(object sender, ShowBuildingsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShowBuildingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ShowBuildingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public Building[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((Building[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void ShowOfficesCompletedEventHandler(object sender, ShowOfficesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShowOfficesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ShowOfficesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public Office[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((Office[])(this.results[0]));
        }
    }
}
